### PR TITLE
Hw2

### PR DESCRIPTION
**Pull request by Inessa1987**
screen_forms1
screen_forms2
screen_table1
screen_table2

### CODE REVIEW

**Comment by spolischook** [comment]
Why it's closed?

**Comment by Inessa1987** [comment]
I created the new PR, where I updated css code and codestyle html. Will you can to review it, if you'll have free time? Thanks) 
https://github.com/Inessa1987/home-work/pull/3



23.10.2018 06:49, Serhii Polishchuk <notifications@github.com>

**Comment by spolischook** [comment]
You can't create few PRs for one HW. I can't review more then once because of a lot of students works. 
I should see your grow in PRs - I don't need perfect code.
Please, don't make more then one PR for one HW, especially when it was reviewed

**Comment by Inessa1987** [comment]
Ok, understandly. Thank you for your help.

**Pull request closed without merging**
